services:
  # База Даних
  postgres:
    image: "pgvector/pgvector:pg16"
    environment:
      - "POSTGRES_DB=travel_agency"
      - "POSTGRES_PASSWORD=1"
      - "POSTGRES_USER=postgres"
    ports:
      - "5933:5432" # Зовнішній доступ (для адміністрування)
    networks:
      - travel-network

  # Java Додаток
  app:
    build: .  # Ця крапка означає "шукай Dockerfile у цій же папці"
    ports:
      - "8086:8086" # Відкриваємо порт сайту назовні
    environment:
      # Передаємо змінні середовища прямо тут
      - DB_LOGIN=postgres
      - DB_PASSWORD=1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/travel_agency
    depends_on:
      - postgres # Чекаємо, поки запуститься база
    networks:
      - travel-network

# Створюємо спільну мережу, щоб контейнери бачили один одного
networks:
  travel-network:
    driver: bridge
