services:
  # База Даних
  postgres:
    image: "pgvector/pgvector:pg16"
    environment:
      - POSTGRES_DB=travel_agency
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5933:5433"
    networks:
      - travel-network

  # Java додаток
  app:
    build: .
    ports:
      - "8086:8086"s
    environment:
      - DB_LOGIN=${DB_LOGIN}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/travel_agency
    depends_on:
      - postgres
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge
