services:
  # База Даних
  postgres:
    image: "pgvector/pgvector:pg16"
    environment:
      - "POSTGRES_DB=travel_agency"
	  - "POSTGRES_USER=${DB_LOGIN}"
	  - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "5933:5432" # Зовнішній доступ (для адміністрування)
    networks:
      - travel-network

  # Java додаток
  app:
    build: .  # Ця крапка означає "шукай Dockerfile у цій же папці"
    ports:
      - "8086:8086" # Відкриваємо порт сайту назовні
    environment:
      # Передаємо змінні середовища
	  - DB_LOGIN=${DB_LOGIN}
	  - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/travel_agency
    depends_on:
      - postgres # Чекаємо, поки запуститься база
    networks:
      - travel-network

# Створюємо спільну мережу, щоб контейнери бачили один одного
networks:
  travel-network:
    driver: bridge
